version: '3.5'
networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 152.23.0.0/16
services:
  db:
    image: mongo:3.0.2
    networks:
      net:
        ipv4_address: 152.23.0.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGODB_USERNAME=test
      - MONGODB_PASSWORD=test123
      - MONGODB_DATABASE=test1
    volumes:
      - ./data/db:/var/micro-data/mongodb/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  app:
    build: .
    environment:
      - bootstrap.memory_lock=true
    tty: true
    ports:
      - 8383:8383
    volumes:
      - .:/source
    privileged: true
    depends_on:
      - db
    networks:
      net:
        ipv4_address: 152.23.0.3
