version: '3.5'
networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK}
services:
  db:
    image: mongo:4.0
    networks:
      net:
        ipv4_address: ${MONGODB_IP}
    volumes:
      - ./data/db:/var/micro-data/mongodb/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  app:
    build: .
    networks:
      net:
        ipv4_address: ${APP_IP}
    environment:
      - bootstrap.memory_lock=true
    tty: true
    volumes:
      - .:/my-football
    privileged: true
    depends_on:
      - db